company/urls.py
from django.urls import path

from company.views.companyEmployeeView import saveEmployee, listEmployee, updateEmployee, recordSystemUserAsEmployee, \
    loadTitle
from company.views.companyView import createCompany, listCompany, updateCompany, deleteCompany
from company.views.departmentView import createDepartment, listDepartment, updateDepartment, deleteDepartment
from company.views.titleView import createCompanyTitle, listTitle, updateTitle, deleteTitle, load_unit, loadDepartment
from company.views.unitView import createUnit, listUnit, updateUnit, deleteUnit, loadUnit
from company.views.userAsEmployeeView import createSignature, displayEmployeeSignature

urlpatterns = [
    path('tit', createCompanyTitle, name='tit'),
    path('lt', listTitle, name='lt'),
    path('upti<str:pk>', updateTitle, name='upti'),
    path('delt<str:pk>', deleteTitle, name='delt'),

    path('dep', createDepartment, name='dep'),
    path('ld', listDepartment, name='ld'),
    path('upde<str:pk>/', updateDepartment, name='upde'),
    path('deld<str:pk>/', deleteDepartment, name='deld'),

    path('cop', createCompany, name='cop'),
    path('lc/', listCompany, name='lc'),
    path('upco/<str:pk>', updateCompany, name='upco'),
    path('delc/<str:pk>', deleteCompany, name='delc'),

    path('cem/', saveEmployee, name='cem'),
    path('lem/', listEmployee, name='lem'),
    path('upem/<str:pk>', updateEmployee, name='upem'),
    path('syem/<int:pk>', recordSystemUserAsEmployee, name='syem'),

    path('cun/', createUnit, name='cun'),
    path('lun/', listUnit, name='lun'),
    path('upun/<str:pk>', updateUnit, name='upun'),
    path('delun/<str:pk>', deleteUnit, name='delun'),
    path('cresig/', createSignature, name='cresig'),
    path('li_em_si/<str:pk>/signature/', displayEmployeeSignature, name='li_em_si'),

    path('ajax/loadUnitDropdown', load_unit, name='loadUnit'),
    path('ajax/loadDepartmentDropdown', loadDepartment, name='load_department'),
    path('ajax/loadTitleDropdown', loadTitle, name='loadTitle')

]

icpars/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("icparsa.urls")),
    path('lem/', include("leaveMan.urls")),
    path('cop/', include("company.urls")),
    path('cor/', include("correspondence.urls")),
    path('filup', include("filemanager.urls")),

]
if settings.DEBUG:
    urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

company/models/companyEmployee.py
from django.db import models

from company.models import Title, Department
from .umumaro import Umumaro


class CompanyEmployee(models.Model):
    number = models.IntegerField(null=True, blank=True)
    emp_code = models.IntegerField(null=True, blank=True)
    first_name = models.CharField(max_length=250, null=True, blank=True)
    last_name = models.CharField(max_length=250, null=True, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    home_phone = models.IntegerField(null=True, blank=True)
    mobile_phone = models.IntegerField(null=True, blank=True)
    home_address = models.CharField(max_length=150, null=True, blank=True)

    hire_date = models.DateField(null=True, blank=True)
    title = models.ForeignKey(Title, on_delete=models.SET_NULL, blank=True, null=True)
    department = models.ForeignKey(Department, on_delete=models.SET_NULL, blank=True, null=True)
    email = models.EmailField(max_length=254, null=True, blank=True)
    role = models.ForeignKey(Umumaro, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    # months_in_institution = models.IntegerField(null=True, blank=True)
    # total_leave_days = models.IntegerField(null=True, blank=True)
    # leave_days_used = models.IntegerField(null=True, blank=True)

company/models/department.py
from django.db import models

from .company import Company


class Department(models.Model):
    number = models.IntegerField()
    name = models.CharField(max_length=150, null=True, blank=True)
    company = models.ForeignKey(Company, on_delete=models.SET_NULL, blank=True, null=True)
    email = models.EmailField(max_length=254, null=True, blank=True)

    def __str__(self):
        return self.name

company/models/title.py
from django.db import models

from .unit import Unit
from .company import Company
from .department import Department


class Title(models.Model):
    number = models.IntegerField()
    name = models.CharField(max_length=150, null=True, blank=True)
    company = models.ForeignKey(Company, on_delete=models.SET_NULL, blank=True, null=True)
    department = models.ForeignKey(Department, on_delete=models.SET_NULL, blank=True, null=True)
    unit = models.ForeignKey(Unit, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return self.name

company/forms/companyForm.py
from django import forms

from company.models.company import Company


class CompanyForm(forms.ModelForm):
    class Meta:
        model = Company
        fields = '__all__'

        widgets = {
            'email': forms.EmailInput(attrs={'placeholder': 'Enter email'})
        }

company/forms/departmentForm.py
from django import forms

from company.models.department import Department


class DepartmentForm(forms.ModelForm):
    class Meta:
        model = Department
        fields = '__all__'

        widgets = {
            'email': forms.EmailInput(attrs={'placeholder': 'Enter email'})
        }

company/forms/userAsEmployeeSignatureForm.py
from django import forms
from django.utils.safestring import mark_safe

from company.models import EmployeeAsUserSignature


# class SignaturePadWidget(forms.Widget):
#     template_name = 'company/employee/signaturePad.html'  # Create this template
#
#     def render(self, name, value, attrs=None, renderer=None):
#         return mark_safe(f'<div id="{name}_signature_pad"></div>')
#
#     def value_from_datadict(self, data, files, name):
#         # Handle form submission and retrieve the signature data
#         return data.get(name, None)


class UserAsEmployeeSignatureForm(forms.ModelForm):
    class Meta:
        model = EmployeeAsUserSignature
        fields = '__all__'

        widgets = {
            'signature_password': forms.PasswordInput(attrs={'placeholder': 'Enter password'}),

        }

company/views/companyEmployeeView.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import redirect, render, get_object_or_404

from company.forms.employeeForm import EmployeeForm
from company.models import CompanyEmployee, Unit, Department, Title
from icparsa.decorators import allowed_users


@login_required(login_url='log')
@allowed_users(allowed_roles=['admin'])
def saveEmployee(request):
    next_number = CompanyEmployee.objects.all().count() + 1
    employeeForm = EmployeeForm(initial={'number': next_number})
    if request.method == 'POST':
        employeeForm = EmployeeForm(request.POST)
        employeeForm.save()
        return redirect('cem')
    context = {'employeeForm': employeeForm}
    return render(request, 'company/employee/employee.html', context)


@login_required(login_url='log')
@allowed_users(allowed_roles=['admin'])
def listEmployee(request):
    employeeList = CompanyEmployee.objects.all()
    context = {'employeeList': employeeList}
    return render(request, 'company/employee/listEmployee.html', context)


def updateEmployee(request, pk):
    emp = CompanyEmployee.objects.get(id=pk)
    empForm = EmployeeForm(instance=emp)
    if request.method == 'POST':
        empForm = EmployeeForm(request.POST, instance=emp)
        if empForm.is_valid():
            empForm.save()
            return redirect('lem')
    context = {'employeeForm': empForm}
    return render(request, 'company/employee/employee.html', context)


def recordSystemUserAsEmployee(request, pk):
    syst_user = get_object_or_404(User, id=pk)
    employee = CompanyEmployee()
    next_number = CompanyEmployee.objects.all().count() + 1
    for field in syst_user._meta.fields:
        if field.name in [f.name for f in employee._meta.fields]:
            setattr(employee, field.name, getattr(syst_user, field.name))
    employee.first_name = syst_user.first_name
    employee.last_name = syst_user.last_name

    if request.method == 'POST':
        empForm = EmployeeForm(request.POST, instance=employee)
        if empForm.is_valid():
            empForm.save()
            # return redirect('syem', pk=employee.pk)
            return redirect('home')

    else:
        empForm = EmployeeForm(initial={'number': next_number}, instance=employee)

    context = {'employeeForm': empForm}
    return render(request, 'company/employee/employee.html', context)


def loadTitle(request):
    department_id = request.GET.get('department_id')
    title = Title.objects.filter(department_id=department_id).order_by('name')
    context = {'title': title}
    return render(request, 'company/title/titleDropDown.html', context)


def load_unit(request):
    department_id = request.GET.get('department_id')
    unit = Unit.objects.filter(department_id=department_id)
    context = {'unit': unit}
    return render(request, 'company/unit/unitDropDown.html', context)


def loadDepartment(request):
    company_id = request.GET.get('company_id')
    department = Department.objects.filter(company_id=company_id)
    context = {'department': department}
    return render(request, 'company/department/departmentDropDown.html', context)

company/views/companyView.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render

from company.forms.companyForm import CompanyForm
from company.models import Company
from icparsa.decorators import allowed_users


@login_required(login_url='log')
@allowed_users(allowed_roles=['admin'])
def createCompany(request):
    next_number = Company.objects.all().count() + 1
    companyForm = CompanyForm(initial={'number': next_number})
    if request.method == 'POST':
        companyForm = CompanyForm(request.POST)
        companyForm.save()
        return redirect('lc')
    context = {'companyForm': companyForm}
    return render(request, 'company/company.html', context)


@login_required(login_url='log')
@allowed_users(allowed_roles=['admin'])
def listCompany(request):
    companyList = Company.objects.all()
    context = {'companyList': companyList}
    return render(request, 'company/listCompany.html', context)


@login_required(login_url='log')
@allowed_users(allowed_roles=['admin'])
def updateCompany(request, pk):
    company = Company.objects.get(id=pk)
    companyForm = CompanyForm(instance=company)
    if request.method == 'POST':
        companyForm = CompanyForm(request.POST, instance=company)
        if companyForm.is_valid():
            companyForm.save()
            return redirect('lc')

    context = {'companyForm': companyForm, 'company': company}
    return render(request, 'company/company.html', context)


@login_required(login_url='log')
@allowed_users(allowed_roles=['admin'])
def deleteCompany(request, pk):
    company = Company.objects.get(id=pk)
    if request.method == 'POST':
        company.delete()
        return redirect('lt')
    context = {'company': company}
    return render(request, 'company/deleteCompany.html', context)

company/views/departmentView.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render

from company.forms.departmentForm import DepartmentForm
from company.models.department import Department
from icparsa.decorators import allowed_users


@login_required(login_url='log')
@allowed_users(allowed_roles=['admin'])
def createDepartment(request):
    next_number = Department.objects.all().count() + 1
    departmentForm = DepartmentForm(initial={'number': next_number})
    if request.method == 'POST':
        departmentForm = DepartmentForm(request.POST)
        departmentForm.save()
        return redirect('ld')
    context = {'departmentForm': departmentForm}
    return render(request, 'company/department.html', context)


@login_required(login_url='log')
def listDepartment(request):
    departmentList = Department.objects.all()
    context = {'listDepartment': departmentList}
    return render(request, 'company/listDepartment.html', context)


@login_required(login_url='log')
@allowed_users(allowed_roles=['admin'])
def updateDepartment(request, pk):
    department = Department.objects.get(id=pk)
    departmentForm = DepartmentForm(instance=department)
    if request.method == 'POST':
        departmentForm = DepartmentForm(request.POST, instance=department)
        if departmentForm.is_valid():
            departmentForm.save()
            return redirect('ld')

    context = {'departmentForm': departmentForm, 'department': department}
    return render(request, 'company/department.html', context)


@login_required(login_url='log')
@allowed_users(allowed_roles=['admin'])
def deleteDepartment(request, pk):
    department = Department.objects.get(id=pk)
    if request.method == 'POST':
        department.delete()
        return redirect('ld')
    context = {'department': department}
    return render(request, 'company/deleteDepartment.html', context)

company/views/titleView.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render

from company.forms.titleForm import TitleForm
from company.models import Unit, Department
from company.models.title import Title
from icparsa.decorators import allowed_users


@login_required(login_url='log')
@allowed_users(allowed_roles=['admin'])
def createCompanyTitle(request):
    next_number = Title.objects.all().count() + 1
    titleForm = TitleForm(initial={'number': next_number})
    if request.method == 'POST':
        titleForm = TitleForm(request.POST)
        titleForm.save()
        return redirect('lt')
    context = {'titleForm': titleForm}
    return render(request, 'company/title.html', context)


@login_required(login_url='log')
def listTitle(request):
    titleList = Title.objects.all()

    context = {'titleList': titleList}
    return render(request, 'company/listTitle.html', context)


@login_required(login_url='log')
@allowed_users(allowed_roles=['admin'])
def updateTitle(request, pk):
    title = Title.objects.get(id=pk)
    titleForm = TitleForm(instance=title)
    if request.method == 'POST':
        titleForm = TitleForm(request.POST, instance=title)
        if titleForm.is_valid():
            titleForm.save()
            return redirect('lt')
    context = {'titleForm': titleForm, 'title': title}
    return render(request, 'company/title.html', context)


@login_required(login_url='log')
@allowed_users(allowed_roles=['admin'])
def deleteTitle(request, pk):
    title = Title.objects.get(id=pk)
    if request.method == 'POST':
        title.delete()
        return redirect('/lt')
    context = {'title': title}
    return render(request, 'company/deleteTitle.html', context)


def load_unit(request):
    department_id = request.GET.get('department_id')
    unit = Unit.objects.filter(department_id=department_id)
    context = {'unit': unit}
    return render(request, 'company/unit/unitDropDown.html', context)


def loadDepartment(request):
    company_id = request.GET.get('company_id')
    department = Department.objects.filter(company_id=company_id)
    context = {'department': department}
    return render(request, 'company/department/departmentDropDown.html', context)

company/views/unitView.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render

from company.forms.unitForm import UnitForm
from company.models import Unit, Department
from icparsa.decorators import allowed_users


@login_required(login_url='log')
@allowed_users(allowed_roles=['admin'])
def createUnit(request):
    next_number = Unit.objects.all().count() + 1
    unitForm = UnitForm(initial={'number': next_number})
    if request.method == 'POST':
        unitForm = UnitForm(request.POST)
        unitForm.save()
        return redirect('lun')
    context = {'unitForm': unitForm}
    return render(request, 'company/unit.html', context)


@login_required(login_url='log')
def listUnit(request):
    unitList = Unit.objects.all()
    context = {'unitList': unitList}
    return render(request, 'company/listUnit.html', context)


@login_required(login_url='log')
@allowed_users(allowed_roles=['admin'])
def updateUnit(request, pk):
    unit = Unit.objects.get(id=pk)
    unitForm = UnitForm(instance=unit)
    if request.method == 'POST':
        unitForm = UnitForm(request.POST, instance=unit)
        if unitForm.is_valid():
            unit.save()
            return redirect('lun')

    context = {'unitForm': unitForm, 'unit': unit}
    return render(request, 'company/unit.html', context)


@login_required(login_url='log')
@allowed_users(allowed_roles=['admin'])
def deleteUnit(request, pk):
    unit = Unit.objects.get(id=pk)
    if request.method == 'POST':
        unit.delete()
        return redirect('/lun')
    context = {'unit': unit}
    return render(request, 'company/deleteUnit.html', context)


def loadUnit(request):
    department_id = request.GET.get('unit_id')
    unit = Unit.objects.filter(department_id=department_id)
    context = {'unit': unit}
    return render(request, 'company/unit/unitDropDown.html', context)


def loadDepartment(request):
    company_id = request.GET.get('department_id')
    department = Department.objects.filter(company_id=company_id)
    context = {'department': department}
    return render(request, 'company/department/departmentDropDown.html', context)

company/templates/company/company.html
{% extends 'icparsa/template/main.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% block content %}


    <div class="row">
        <div class="col-md">
            <div class="card">
                <div class="card-header">
                    <h4 style="font-size: smaller; text-align: center">Record New Company</h4>
                </div>
            </div>
        </div>
    </div>
    <br>
    <div class="row">
        <div class="col-md">
            <div class="card card-body" style="font-size: x-small">
                <form method="post" action="" id="contractFormId"
                      data-mebdep-url= {% url 'load_department_members_url' %}>
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="form-group col-2">
                            {{ companyForm.number|as_crispy_field }}
                        </div>
                        <div class="form-group col-2">
                            {{ companyForm.name|as_crispy_field }}
                        </div>

                    </div>
                    <br>
                    <input type="submit" name="Send" class="btn btn-sm btn-info">
                    <a href="lc/" class="btn btn-sm btn-info">
                        <i class="fa-solid fa-list"></i> List
                    </a>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

company/templates/company/deleteCompany.html
{% extends 'icparsa/template/main.html' %}
{% load crispy_forms_filters %}
{% block content %}
    <br>
    <div class="row text-center">
        <div class="col-md-6">
            <div class="card card-body">
                <p>Are you sure you want to delete "{{ company }}"? </p>
                <form action="{% url 'delCo' company.id %}" method="post">
                    {% csrf_token %}
                    <a class="btn btn-warning" href="{% url 'lc' %}"><i class="fa-solid fa-xmark"></i>Cancel</a>
                    <button class="btn btn-danger" type="submit" name="Confirm">
                        <i class="fa-solid fa-check"></i> Confirm
                    </button>


                </form>
            </div>
        </div>
    </div>

{% endblock %}

company/templates/company/deleteDepartment.html
{% extends 'icparsa/template/main.html' %}
{% load crispy_forms_filters %}
{% block content %}
    <br>
    <div class="row text-center">
        <div class="col-md-6">
            <div class="card card-body">
                <p>Are you sure you want to delete "{{ department }}"? </p>
                <form action="{% url 'deld' department.id %}" method="post">
                    {% csrf_token %}
                    <a class="btn btn-warning" href="{% url 'ld' %}"><i class="fa-solid fa-xmark"></i>Cancel</a>
                    <button class="btn btn-danger" type="submit" name="Confirm">
                        <i class="fa-solid fa-check"></i> Confirm
                    </button>


                </form>
            </div>
        </div>
    </div>

{% endblock %}

company/templates/company/deleteTitle.html
{% extends 'icparsa/template/main.html' %}
{% load crispy_forms_filters %}
{% block content %}
    <br>
    <div class="row text-center">
        <div class="col-md-6">
            <div class="card card-body">
                <p>Are you sure you want to delete "{{ title }}"? </p>
                <form action="{% url 'delt' title.id %}" method="post">
                    {% csrf_token %}
                    <a class="btn btn-warning" href="{% url 'lt' %}"><i class="fa-solid fa-xmark"></i>Cancel</a>
                    <button class="btn btn-danger" type="submit" name="Confirm">
                        <i class="fa-solid fa-check"></i> Confirm
                    </button>


                </form>
            </div>
        </div>
    </div>

{% endblock %}

company/templates/company/deleteUnit.html
{% extends 'icparsa/template/main.html' %}
{% load crispy_forms_filters %}
{% block content %}
    <br>
    <div class="row text-center">
        <div class="col-md-6">
            <div class="card card-body">
                <p>Are you sure you want to delete "{{ unit }}"? </p>
                <form action="{% url 'delun' unit.id %}" method="post">
                    {% csrf_token %}
                    <a class="btn btn-warning" href="{% url 'lun' %}"><i class="fa-solid fa-xmark"></i>Cancel</a>
                    <button class="btn btn-danger" type="submit" name="Confirm">
                        <i class="fa-solid fa-check"></i> Confirm
                    </button>


                </form>
            </div>
        </div>
    </div>

{% endblock %}

company/templates/company/department.html
{% extends 'icparsa/template/main.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% block content %}


    <div class="row">
        <div class="col-md">
            <div class="card">
                <div class="card-header">
                    <h4 style="font-size: smaller; text-align: center">Record New Department</h4>
                </div>
            </div>
        </div>
    </div>
    <br>
    <div class="row">
        <div class="col-md">
            <div class="card card-body" style="font-size: x-small">
                <form method="post" action="" id="contractFormId"
                      data-mebdep-url= {% url 'load_department_members_url' %}>
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="form-group col-2">
                            {{ departmentForm.number|as_crispy_field }}
                        </div>
                        <div class="form-group col-2">
                            {{ departmentForm.name|as_crispy_field }}
                        </div>
                        <div class="form-group col-2">
                            {{ departmentForm.company|as_crispy_field }}
                        </div>

                        <div class="form-group col-2">
                            {{ departmentForm.email|as_crispy_field }}
                        </div>
                    </div>
                    <br>
                    <input type="submit" name="Send" class="btn btn-sm btn-info">
                    <a href="/cop/ld" class="btn btn-sm btn-info">
                        <i class="fa-solid fa-list"></i> List
                    </a>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

company/templates/company/title.html
{% extends 'icparsa/template/main.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% block content %}


    <div class="row">
        <div class="col-md">
            <div class="card">
                <div class="card-header">
                    <h4 style="font-size: smaller; text-align: center">Record New Title</h4>
                </div>
            </div>
        </div>
    </div>
    <br>
    <div class="row">
        <div class="col-md">
            <div class="card card-body" style="font-size: x-small">
                <form method="post" action="" id="titleFormId"
                      unit_url_loader="{% url 'loadUnit' %}"
                      department_url_loader="{% url 'load_department' %}">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="form-group col-2">
                            {{ titleForm.number|as_crispy_field }}
                        </div>
                        <div class="form-group col-2">
                            {{ titleForm.name|as_crispy_field }}
                        </div>
                        <div class="form-group col-2">
                            {{ titleForm.company|as_crispy_field }}
                        </div>
                        <div class="form-group col-2">
                            {{ titleForm.department|as_crispy_field }}
                        </div>
                        <div class="form-group col-2">
                            {{ titleForm.unit|as_crispy_field }}
                        </div>
                    </div>
                    <br>
                    <input type="submit" name="Send" class="btn btn-sm btn-info">
                    <a href="/cop/lt" class="btn btn-sm btn-info">
                        <i class="fa-solid fa-list"></i> List
                    </a>
                </form>
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script>
        $("#id_company").on("change", function () {
            const url = $("#titleFormId").attr("department_url_loader");
            const companyId = $(this).val();
            $.ajax({
                url: url,
                data: {'company_id': companyId},
                success: function (data) {
                    console.log(data);
                    $("#id_department").html(data)
                }
            });
        });
    </script>
    <script>

        $("#id_department").on("change", function () {
            const url = $("#titleFormId").attr("unit_url_loader");
            const departmentId = $(this).val();
            $.ajax({
                url: url,
                data: {'department_id': departmentId},
                success: function (data) {
                    console.log(data);
                    $("#id_unit").html(data)
                }
            });
        });

    </script>

{% endblock %}

company/templates/company/unit.html
{% extends 'icparsa/template/main.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% block content %}


    <div class="row">
        <div class="col-md">
            <div class="card">
                <div class="card-header">
                    <h4 style="font-size: smaller; text-align: center">Record New Unit</h4>
                </div>
            </div>
        </div>
    </div>
    <br>
    <div class="row">
        <div class="col-md">
            <div class="card card-body" style="font-size: x-small">
                <form method="post" action="" id="unitFormId"
                      department_url_loader= {% url 'load_department' %}>
                    {% csrf_token %}
                    <div class="row">
                        <div class="form-group col-2">
                            {{ unitForm.number|as_crispy_field }}
                        </div>
                        <div class="form-group col-2">
                            {{ unitForm.name|as_crispy_field }}
                        </div>


                    </div>
                    <div class="row">
                        <div class="form-group col-2">
                            {{ unitForm.company|as_crispy_field }}
                        </div>
                        <div class="form-group col-2">
                            {{ unitForm.department|as_crispy_field }}
                        </div>

                    </div>
                    <br>
                    <input type="submit" name="Send" class="btn btn-sm btn-info">
                    <a href="/cop/lun" class="btn btn-sm btn-info">
                        <i class="fa-solid fa-list"></i> List
                    </a>
                </form>
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script>
        $("#id_company").on("change", function () {
            const url = $("#unitFormId").attr("department_url_loader");
            const companyId = $(this).val();
            $.ajax({
                url: url,
                data: {'company_id': companyId},
                success: function (data) {
                    console.log(data);
                    $("#id_department").html(data)
                }
            });
        });

    </script>

{#    <script>#}
{#        $("#id_unit").on("change", function () {#}
{#            const url = $("unitFormId").attr("department_url_loader");#}
{#            const unitId = $(this).val();#}
{#            $.ajax({#}
{#                url: url,#}
{#                data: {'unit_id': unitId},#}
{#                success: function (data) {#}
{#                    console.log(data);#}
{#                    $("#id_unit").html(data)#}
{#                }#}
{#            })#}
{#        });#}
{#    </script>#}

{% endblock %}