icpars/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("icparsa.urls")),
    path('lem/', include("leaveMan.urls")),
    path('cop/', include("company.urls")),
    path('cor/', include("correspondence.urls")),
    path('filup', include("filemanager.urls")),

]
if settings.DEBUG:
    urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

leaveMan/urls.py
from django.urls import path

from leaveMan.views import leadDash
from leaveMan.views.leave_view import *

urlpatterns = [
    path('ld/', leadDash, name='ld'),
    path('rl/', recordLeave, name='rl'),
    path('lil/', listLeave, name='lil'),
    path('ul/<str:pk>', updateLeave, name='ul'),
    path('uls/<int:pk>/', updateLeaveStatus, name='uls'),
    path('gl/<int:pk>/', give_leave, name='gl'),
    path('ajax/loadTitle', loadTitle, name='loadTitle'),
    path('holidays/<str:country>/', holidays_view, name='holidays'),
    path('phapi/<str:country>/<int:year>/', publicHolidaysAPICaller, name='phapi'),
    path('loadleave/<int:pk>', generateLeave, name='loadleave'),
    path('myLeaves', my_leave, name='myLeaves'),

]

leaveMan/models/leave.py
from django.db import models

from company.models import Department, Title, CompanyEmployee


class Leave(models.Model):
    STATUS_OF_LEAVE = [
        ('PENDING', 'PENDING'),
        ('APPROVED', 'APPROVED'),
        ('DENIED', 'DENIED'),
        ('DONE', 'DONE'),
    ]

    number = models.IntegerField(null=True, blank=True)
    employee = models.ForeignKey(CompanyEmployee, on_delete=models.CASCADE, null=True, blank=True)
    months_in_institution = models.IntegerField(null=True, blank=True)
    total_leave_days = models.IntegerField(null=True, blank=True)
    leave_days_used = models.IntegerField(null=True, blank=True, default=0)
    leave_days = models.IntegerField(null=True, blank=True, default=0)
    outDate = models.DateField(null=True, blank=True)
    inDate = models.DateField(null=True, blank=True)
    leave_status = models.CharField(max_length=100, choices=STATUS_OF_LEAVE, default='PENDING')
    approval_one = models.BinaryField(null=True, blank=True)

leaveMan/models/leaveDecision.py
from django.contrib.auth.models import User
from django.db import models

from company.models import CompanyEmployee, EmployeeAsUserSignature
from leaveMan.models import Leave


class LeaveDecision(models.Model):
    leave = models.ForeignKey(Leave, on_delete=models.CASCADE)
    requestingEmployee = models.ForeignKey(CompanyEmployee, related_name='requested_leaves', on_delete=models.CASCADE)
    approvingEmployee = models.ForeignKey(User, related_name='approved_leaves', on_delete=models.CASCADE)
    decisionStatus = models.CharField(max_length=100, null=True, blank=True, default='Pending')
    signature = models.ForeignKey(EmployeeAsUserSignature, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return f"Decision for leave of {self.leave.employee.first_name} ({self.decisionStatus})"

leaveMan/forms/leaveForm.py
from django import forms

from company.models import Department, Title
from leaveMan.models import Leave


class LeaveForm(forms.ModelForm):
    number = forms.IntegerField(widget=forms.NumberInput(attrs={'readonly': 'True'}))
    first_name = forms.CharField(max_length=250, widget=forms.TextInput(attrs={'readonly': 'True'}))
    last_name = forms.CharField(max_length=250, widget=forms.TextInput(attrs={'readonly': 'True'}))
    department = forms.ModelChoiceField(queryset=Department.objects.all(),
                                        widget=forms.Select(attrs={'readonly': 'readonly'}))
    title = forms.ModelChoiceField(queryset=Title.objects.all(), widget=forms.Select(attrs={'readonly': 'readonly'}))
    home_phone = forms.IntegerField(widget=forms.NumberInput(attrs={'readonly': 'True'}))
    mobile_phone = forms.IntegerField(widget=forms.NumberInput(attrs={'readonly': 'True'}))
    home_address = forms.CharField(max_length=150, widget=forms.TextInput(attrs={'readonly': 'True'}))
    birth_date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date', 'readonly': 'True'}, ))
    hire_date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date', 'readonly': 'True'}), label='Hired On')
    inDate = forms.DateField(widget=forms.DateInput(attrs={'type': 'date', 'readonly': 'True'}), label='Returning On')
    outDate = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}), label='Leaving On')
    leave_days_used = forms.IntegerField(widget=forms.NumberInput(attrs={'readonly': 'True'}), label='Consumed Days')
    # leave_days = forms.IntegerField(widget=forms.NumberInput(attrs={'readonly': 'True'}))
    months_in_institution = forms.IntegerField(widget=forms.NumberInput(attrs={'readonly': 'True'}))
    total_leave_days = forms.IntegerField(widget=forms.NumberInput(attrs={'readonly': 'True'}))

    class Meta:
        model = Leave
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(LeaveForm, self).__init__(*args, **kwargs)
        self.fields['leave_status'].disabled = True

leaveMan/forms/signaturePasswordForm.py
from django import forms


class SignaturePasswordForm(forms.Form):
    signature_password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Enter password'}),
                                         label='Signature Password')

leaveMan/views/leave_view.py
import base64
import io
import json
import tempfile
from datetime import date

import requests
from PIL import UnidentifiedImageError
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import check_password
from django.contrib.auth.models import User
from django.db import models
from django.db.models import Sum, Q
from django.http import JsonResponse, FileResponse
from django.shortcuts import render, redirect, get_object_or_404
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfgen import canvas
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Image, Spacer, Paragraph
from PIL import Image as PILImage, UnidentifiedImageError

from company.models import CompanyEmployee, Department, Title, EmployeeAsUserSignature, Unit
from icparsa.decorators import allowed_users
from leaveMan.forms.leaveForm import LeaveForm
from leaveMan.forms.signaturePasswordForm import SignaturePasswordForm
from leaveMan.models import Leave, LeaveDecision
from io import BytesIO


@login_required(login_url='log')
@allowed_users(allowed_roles=['admin', 'leaveManager'])
@login_required(login_url='log')
def recordLeave(request):
    next_number = Leave.objects.all().count() + 1
    empForm = LeaveForm(initial={'number': next_number})
    if request.method == 'POST':
        empForm = LeaveForm(request.POST)
        empForm.save()
        return redirect('lil')

    context = {'empForm': empForm}
    return render(request, 'leaveMan/leave/leave.html', context)


@login_required(login_url='log')
@allowed_users(allowed_roles=['admin', 'leaveManager', 'director', 'manager'])
def listLeave(request):
    leaveDecisionMakersGroup = Q(groups__name='leaveDecisionMakers')
    adminsGroup = Q(groups__name='admin')
    leaveDecisionMakersMember = User.objects.filter(leaveDecisionMakersGroup)
    adminsGroupMember = User.objects.filter(adminsGroup)

    leaveDecisions = {ld.leave.id: ld.decisionStatus for ld in
                      LeaveDecision.objects.filter(approvingEmployee=request.user)}
    user_role = request.user.groups.first().name

    user_employee = CompanyEmployee.objects.get(email=request.user.email)

    employee_title = user_employee.title.name.lower() if user_employee.title else ''

    if 'manager' in employee_title:
        leaveList = Leave.objects.filter(
            models.Q(employee__title__unit=user_employee.title.unit) |
            models.Q(employee__title__name__icontains='manager',
                     employee__department=user_employee.department)).order_by('number')

    elif 'director' in employee_title:
        leaveList = Leave.objects.filter(
            Q(employee__department=user_employee.department) |
            Q(employee__title__name__icontains='director')).order_by('number')

    elif 'admin' in employee_title:
        leaveList = Leave.objects.all().order_by('number')

    elif 'ceo' in employee_title:
        leaveList = Leave.objects.all().order_by('number')

    else:
        leaveList = Leave.objects.none()

    context = {'leaveList': leaveList, 'leaveDecisionMakersMember': leaveDecisionMakersMember,
               'adminsGroupMember': adminsGroupMember, 'leaveDecisions': leaveDecisions}
    return render(request, 'leaveMan/leave/leaveList.html', context)


def my_leave(request):
    employee_as_user = CompanyEmployee.objects.get(id=request.user.id)
    employee_leaves = Leave.objects.filter(employee=employee_as_user).order_by('inDate')
    context = {'employee_leaves': employee_leaves, 'employee_as_user': employee_as_user}
    return render(request, 'leaveMan/leave/employee_leaves.html', context)


@login_required(login_url='log')
@allowed_users(allowed_roles=['admin', 'leaveManager'])
def updateLeave(request, pk):
    leave = Leave.objects.get(id=pk)
    leaveForm = LeaveForm(instance=leave)
    if request.method == 'POST':
        leaveForm = LeaveForm(request.POST, instance=leave)
        if leaveForm.is_valid():
            leaveForm.save()
            return redirect('lil')
    context = {'empForm': leaveForm}
    return render(request, 'leaveMan/leave/leave.html', context)


def updateLeaveStatus(request, pk):
    leaveId = request.POST.get('leave_id')
    signaturePassword = request.POST.get('password')
    leave = get_object_or_404(Leave, id=leaveId)
    userSignature = get_object_or_404(EmployeeAsUserSignature, employee=request.user)

    if check_password(signaturePassword, userSignature.signature_password):
        if leave.leave_status == 'PENDING':
            leave.leave_status = 'APPROVED'
        elif leave.leave_status == 'APPROVED':
            leave.leave_status = 'DENIED'
        else:
            leave.leave_status = 'PENDING'

        leave.save()

        existingLeaveDecision = LeaveDecision.objects.filter(
            leave=leave,
            approvingEmployee=request.user,
        ).first()

        if existingLeaveDecision:
            existingLeaveDecision.decisionStatus = leave.leave_status
            existingLeaveDecision.signature = userSignature
            existingLeaveDecision.save()

        else:
            newDecision = LeaveDecision.objects.create(
                leave=leave,
                requestingEmployee=leave.employee,
                approvingEmployee=request.user,
                decisionStatus=leave.leave_status,
                signature=userSignature,
            )
            newDecision.save()
        if 'Manager' not in leave.employee.title.name and 'Director' not in leave.employee.title.name:
            manager = get_object_or_404(CompanyEmployee, department=leave.employee.department,
                                        title__name__icontains='Manager')
            director = get_object_or_404(CompanyEmployee, department=leave.employee.department,
                                         title__name__icontains='Director')
            managerSignature = get_object_or_404(EmployeeAsUserSignature, employee=manager)
            directorSignature = get_object_or_404(EmployeeAsUserSignature, employee=director)

            LeaveDecision.objects.get_or_create(
                leave=leave,
                requestingEmployee=leave.employee,
                approvingEmployee=request.user,
                defaults={'decisionStatus': 'PENDING', 'signature': managerSignature}
            )

            LeaveDecision.objects.get_or_create(
                leave=leave,
                requestingEmployee=leave.employee,
                approvingEmployee=request.user,
                defaults={'decisionStatus': 'PENDING', 'signature': directorSignature}
            )
        elif 'Manager' in leave.employee.title.name:
            director = get_object_or_404(CompanyEmployee, department=leave.employee.department, title__name='Director')
            directorSignature = get_object_or_404(EmployeeAsUserSignature, employee=director)

            LeaveDecision.objects.get_or_create(
                leave=leave,
                requestingEmployee=leave.employee,
                approvingEmployee=request.user,
                defaults={'decisionStatus': 'PENDING', 'signature': directorSignature}
            )

        return JsonResponse({'success': True, 'new_status': leave.leave_status})
    else:
        return JsonResponse({'success': False, 'error': 'Incorrect password'})


@login_required(login_url='log')
# @allowed_users(allowed_roles=['admin', 'leaveManager', 'end_user'])
def give_leave(request, pk):
    emp = get_object_or_404(CompanyEmployee, id=pk)
    next_number = Leave.objects.all().count() + 1
    if request.method == 'POST':
        leaveForm = LeaveForm(request.POST)
        if leaveForm.is_valid():
            leave = leaveForm.save(commit=False)
            leave.employee = emp
            leave.first_name = emp.first_name
            leave.last_name = emp.last_name
            leave.birth_date = emp.birth_date
            # leave.department = employee.department
            leave.department = Department.objects.get(name=emp.department)
            leave.title = emp.title
            leave.hire_date = emp.hire_date
            leave.home_phone = emp.home_phone
            leave.mobile_phone = emp.mobile_phone
            leave.home_address = emp.home_address
            leave.months_in_institution = (date.today() - emp.hire_date).days // 30
            conflictedLeaves = Leave.objects.filter(Q(employee__department=emp.department),
                                                    Q(outDate__lte=leave.inDate, inDate__gte=leave.outDate))

            if conflictedLeaves.exists():
                messages.error(request, 'Department allow only one employee at time')
                return redirect('lem')
            leave.save()

            userSignature = get_object_or_404(EmployeeAsUserSignature, employee=request.user)
            LeaveDecision.objects.create(
                leave=leave,
                requestingEmployee=leave.employee,
                approvingEmployee=request.user,
                decisionStatus='REQUESTING',
                signature=userSignature
            )

            if 'Manager' not in emp.title.name and 'Director' not in emp.title.name:
                manager = get_object_or_404(CompanyEmployee, department=emp.department,
                                            title__name__icontains='Manager')
                director = get_object_or_404(CompanyEmployee, department=emp.department,
                                             title__name__icontains='Director')
                managerSignature = get_object_or_404(EmployeeAsUserSignature, employee=manager)
                directorSignature = get_object_or_404(EmployeeAsUserSignature, employee=director)

leaveMan/views/views.py
from django.shortcuts import render


# Create your views here.
def leadDash(request):
    return render(request, 'leaveMan/leaveDash.html')

leaveMan/templates/leaveMan/leave/employee_leaves.html
{% extends 'icparsa/template/main.html' %}
{% block content %}
    <div class="row">
        <div class="col-md">
            <div class="card card-body" style="font-size: x-small">
                <div class="contract-container" style="height: 450px; overflow: auto;">
                    <table class="table table-hover table-bordered table-sm small " id="tbl">
                        <thead class="thead-light">
                        <tr>
                            <th>Leave Number</th>
                            <th>First Name</th>
                            <th>Last Name</th>
                            <th>Start Date</th>
                            <th>End Date</th>
                            <th>Leave Status</th>
                            <th>Total Leave Days</th>
                            <th>Leave Days</th>
                            <th>Used Leave Days</th>
                            <th>Generate</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for leave in employee_leaves %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{ leave.employee.first_name }}</td>
                                <td>{{ leave.employee.last_name }}</td>
                                <td>{{ leave.inDate }}</td>
                                <td>{{ leave.outDate }}</td>
                                <td>{{ leave.leave_status }}</td>
                                <td>{{ leave.total_leave_days }}</td>
                                <td>{{ leave.leave_days }}</td>
                                <td>{{ leave.leave_days_used }}</td>
                                <td><a href="{% url 'loadleave' leave.id %}">Generate
                                    <i class="fa fa-download" aria-hidden="true"></i>
                                </a></td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

leaveMan/templates/leaveMan/leave/leave.html
{% extends 'icparsa/template/main.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% block content %}

    <div class="row">
        <div class="col-md">
            <div class="card">
                <div class="card-header">
                    <h4 style="font-size: smaller; text-align: center">Record Leave</h4>
                </div>
            </div>
        </div>
    </div>
    <br>

    <div class="row">
        <div class="col-md">
            <form method="post" action="" id="leaveFormId" leave-data-url= {% url 'loadTitle' %}>
                {% csrf_token %}
                <div class="card card-body" style="font-size: x-small">

                    <fieldset class="border rounded-2 shadow bg-white shadow-inner border-success p-2 mt-2">
                        <div class="col-sm-12 p-2  rounded-1 shadow-sm">
                            <legend class="w-auto"><h6>-:</h6></legend>
                            <div class="row">
                                <div class="form-group col-2">
                                    {{ empForm.number|as_crispy_field }}
                                </div>
                                <div class="form-group col-2">
                                    {{ empForm.birth_date|as_crispy_field }}
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group col-2">
                                    {{ empForm.first_name|as_crispy_field }}
                                </div>
                                <div class="form-group col-2">
                                    {{ empForm.last_name|as_crispy_field }}
                                </div>
                            </div>

                            <div class="row">

                            </div>
                        </div>
                    </fieldset>
                    <fieldset class="border rounded-2 shadow bg-white border-success p-2 mt-2">

                        <div class="col-sm-12 p-2  rounded-1 shadow-sm">
                            <legend class="w-auto"><h6>-:</h6></legend>
                            <div class="row">

                                <div class="form-group col-2">
                                    {{ empForm.department|as_crispy_field }}
                                </div>

                                <div class="form-group col-2">
                                    {{ empForm.title|as_crispy_field }}
                                </div>


                                <div class="form-group col-2">
                                    {{ empForm.hire_date|as_crispy_field }}
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group col-2">
                                    {{ empForm.home_phone|as_crispy_field }}
                                </div>
                                <div class="form-group col-2">
                                    {{ empForm.mobile_phone|as_crispy_field }}
                                </div>
                                <div class="form-group col-2">
                                    {{ empForm.home_address|as_crispy_field }}
                                </div>
                            </div>
                        </div>
                    </fieldset>
                    <fieldset class="border rounded-2 shadow bg-white border-success p-2 mt-2">
                        <legend class="w-auto"><h6>-:</h6></legend>
                        <div class="row p-2 mt-1">
                            <div class="col-sm-9 p-2  rounded-1 shadow-sm border-info">
                                <div class="row">
                                    <div class="form-group col-sm-3">
                                        {{ empForm.months_in_institution |as_crispy_field }}
                                    </div>
                                    <div class="form-group col-sm-3">
                                        {{ empForm.total_leave_days |as_crispy_field }}
                                    </div>
                                    <div class="form-group col-sm-3">
                                        {{ empForm.leave_days_used |as_crispy_field }}
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="form-group col-sm-3">
                                        {{ empForm.outDate |as_crispy_field }}
                                    </div>
                                    <div class="form-group col-sm-3">
                                        {{ empForm.leave_days |as_crispy_field }}
                                    </div>
                                    <div class="form-group col-sm-3">
                                        {{ empForm.inDate |as_crispy_field }}
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="form-group col-sm-3">
                                        {{ empForm.leave_status |as_crispy_field }}
                                    </div>

                                </div>
                            </div>
                            <div class="col-sm-3 p-2  rounded-1 shadow-sm  border-warning">
                                <div class="row p-2" id="remainingDays">

                                </div>

                                <div class="row p-2">
                                    <table class="table table-striped table-bordered table-sm small" style="max-height: 100px;
                                                                                                              overflow: auto;
                                                                                                              display:inline-block">
                                        <tr>
                                            <td>Name</td>
                                            <td>From</td>
                                            <td>To</td>
                                        </tr>
                                        {% for l in ongoingLeaves %}
                                            <tr>
                                                <td>{{ l.employee.first_name }}</td>
                                                <td>{{ l.outDate }}</td>
                                                <td>{{ l.inDate }}</td>
                                            </tr>
                                        {% endfor %}
                                    </table>
                                </div>
                                <div class="row p-2">
                                    <p class="warning">NB: you are not allowed to take leave if there is member of your
                                        unit on
                                        leave</p>
                                </div>

                            </div>
                        </div>
                    </fieldset>
                </div>
                <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static"
                     data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel"
                     aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <div class="alert alert-success" role="alert">
                                    <div class="d-flex gap-4">
                                        <span><i class="fa-solid fa-circle-check icon-success"></i></span>
                                        <div>
                                            Leave Request was Sent.
                                        </div>
                                    </div>
                                </div>
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">

                                </button>
                            </div>
                            <div class="modal-body">
                                Please wait for approval !
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-success" data-bs-dismiss="modal"
                                        id="closeButton">Ok
                                </button>
                                {#                                <button type="button" class="btn btn-primary" data-bs-dismiss="modal"#}
                                {#                                        id="addContract">Add Contract#}
                                {#                                </button>#}
                            </div>
                        </div>
                    </div>
                </div>
                <br>
                <input type="submit" name="Send" class="btn btn-sm btn-info">
                <a href="/cop/lem" class="btn btn-sm btn-info">
                    <i class="fa-solid fa-list"></i> List
                </a>
            </form>
        </div>
    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <script>
        $(document).ready(function () {
            // Set initial leave days used value
            const initialLeaveDaysUsed = $("#id_leave_days_used").val();
            const totalLeaveDays = $("#id_total_leave_days").val();

            // Get public holidays
            let publicHolidays;
            let umwakaTurimo = new Date().getFullYear()
            $.ajax({
                url: '/lem/phapi/rw/' + umwakaTurimo + '/',
                success: function (data) {
                    publicHolidays = data;
                }
            });

            // Hire date change event
            $('#id_hire_date').on('change', function () {
                const hireDate = new Date($(this).val());
                const currentDate = new Date();

                const monthsInInstitution = (currentDate.getFullYear() - hireDate.getFullYear()) * 12 + (currentDate.getMonth() - hireDate.getMonth());
                $("#id_months_in_institution").val(monthsInInstitution)

                leave_Days = monthsInInstitution * 1.5;
                $("#id_total_leave_days").val(leave_Days);
            });

            // Leave days input event with validation
            $("#id_leave_days").on("input", function () {
                let leaveDays = Number($(this).val());
                let usedLeaveDays = Number(initialLeaveDaysUsed);
                let remainingLeaveDays = totalLeaveDays - usedLeaveDays;

                if (leaveDays > remainingLeaveDays) {
                    alert("You cannot take more leave days than the remaining leave days.");
                    $(this).val(remainingLeaveDays);
                    leaveDays = remainingLeaveDays;
                }

                let totalLeaveDaysUsed = usedLeaveDays + leaveDays;
                $("#id_leave_days_used").val(totalLeaveDaysUsed);

                // Calculate the return date (inDate)
                let outDate = new Date($("#id_outDate").val());
                let inDate = new Date(outDate);
                let count = 0;
                while (count < leaveDays) {
                    inDate.setDate(inDate.getDate() + 1);
                    // Check if the day is a weekend or a public holiday
                    if (inDate.getDay() !== 0 && inDate.getDay() !== 6 && !publicHolidays.includes(inDate.toISOString().split('T')[0])) {
                        count++;
                    }
                }
                $("#id_inDate").val(inDate.toISOString().split('T')[0]);
            });

            // Department change event
            $("#id_department").on('change', function () {
                const url = $("#leaveFormId").attr("leave-data-url");
                const departmentId = $(this).val();
                $.ajax({
                    url: url,
                    data: {'department_id': departmentId},
                    success: function (data) {
                        console.log(data);
                        $("#id_title").html(data);
                    }
                });
            });

            let allowedDays = totalLeaveDays - initialLeaveDaysUsed
            $("#remainingDays").text("Remaining Days = " + allowedDays)
        });

    </script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    {% if messages %}
        {% for message in messages %}
            {% if message.tags == 'success' %}
                <script>
                    $(document).ready(function () {
                        $('#staticBackdrop').modal('show');
                    });
                </script>
                <script>
                    $(document).ready(function () {
                        $('#closeButton').on('click', function () {
                            window.location.href = "{% url 'lem' %}";
                        });
                    });
                </script>
                <script>
                    $(document).ready(function () {
                        $('#addContract').on('click', function () {
                            window.location.href = "/con/";
                        });
                    });
                </script>

            {% endif %}
        {% endfor %}
    {% endif %}
{% endblock %}