icpars/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("icparsa.urls")),
    path('lem/', include("leaveMan.urls")),
    path('cop/', include("company.urls")),
    path('cor/', include("correspondence.urls")),
    path('filup', include("filemanager.urls")),

]
if settings.DEBUG:
    urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

icparsa/urls.py
from django.urls import include, path

from . import views
from .views import contractView, institutionView, loginView, spTypeView, departmentView, departmentMemberView, \
    notificationView, contractSettingView
from .views.notificationView import sendEmailNotification

urlpatterns = [

    path('', views.home, name='home'),
    path('icparsa/', include("django.contrib.auth.urls")),

    path('con/', contractView.recordContract, name="cont"),
    path('upcon/<str:pk>', contractView.updateContract, name="upcon"),
    path('delCo/<int:pk>', contractView.deleteContract, name="delCo"),
    path('conts/', contractView.listContracts, name="conts"),
    path('srch/', contractView.searchWithDates, name='srch'),
    path('sic/', contractView.searchCompanyName, name='sic'),
    path('upStat/<str:pk>', contractView.updateContractStatus, name='upStat'),
    path('excon/', contractView.exportContractExport, name='excon'),
    path('renewCon/<int:pk>', contractView.contractRenew, name='renewCon'),

    path('inst/', institutionView.recordInstitute, name="inst"),
    path('upins/<int:pk>', institutionView.updateInstitution, name="upins"),
    path('insts/', views.listCustomers, name="insts"),
    path('delinst/<int:pk>', institutionView.deleteInstitution, name="delinst"),
    path('schin/', institutionView.searchWithCompanyName, name="schin"),
    path('spt/', spTypeView.createNewType, name='spt'),
    path('lspt/', spTypeView.listSecondPartyType, name='lspt'),

    path('dep/', departmentView.createDepartment, name='dep'),
    path('ldep/', departmentView.listDepartment, name='ldep'),
    path('dem/', departmentMemberView.createDepartmentMember, name='dem'),
    path('ldem/', departmentMemberView.listDepartmentMember, name='ldem'),
    path('ajax/load_department_members', departmentMemberView.load_department_members,
         name='load_department_members_url'),
    path('updem/<str:pk>', departmentMemberView.updateDepartmentMember, name='updem'),
    path('updep/<str:pk>', departmentView.updateDepartment, name='updep'),

    path('log/', loginView.loger, name='log'),
    path('lout/', loginView.signe_out, name='lout'),
    path('reg/', loginView.registerPage, name='reg'),
    path('lsu/', loginView.listSystemUsers, name='lsu'),

    path('note/', notificationView.sendEmail, name='note'),
    path('conset/', contractSettingView.setupContract, name='conset'),
    path('liconset/', contractSettingView.listContractSetup, name='liconset'),
    path('upConSet/<str:pk>', contractSettingView.updateContractSetup, name='upConSet'),
    path('delConSet/<str:pk>', contractSettingView.deleteContractSetup, name='delConSet'),
    path('consetName/', contractSettingView.createContractSettingName, name='consetName'),
    path('LiCoSeNa/', contractSettingView.listContractSettingName, name='LiCoSeNa'),
    path('upLiCoSeNa/<str:pk>/', contractSettingView.updateContractSettingName, name='upLiCoSeNa'),
    path('ajax/load_contract_type', contractSettingView.loadContractSettingType,
         name='load_contract_type_url'),
]

icparsa/models/departmentMemberModel.py
from django.db import models

from .departmentModel import Department


class DepartmentMember(models.Model):
    number = models.IntegerField(null=True)
    name = models.CharField(max_length=150, null=True, blank=True)
    department = models.ForeignKey(Department, null=True, blank=True, on_delete=models.SET_NULL)
    email = models.CharField(max_length=250, null=True, blank=True)

    def __str__(self):
        return self.name

icparsa/models/models.py
from django.db import models

# Create your models here.
from icparsa.models.secondPartyType import SecondPartyType
from .contractSetting import ContractSetting, ContractSettingName
from .departmentMemberModel import DepartmentMember
from .departmentModel import Department


class SecondParty(models.Model):
    date_created = models.DateField(auto_now_add=True, null=True)
    number = models.IntegerField(null=True)
    name = models.CharField(max_length=250, null=True)
    spType = models.ForeignKey(SecondPartyType, null=True, blank=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.name


class Contract(models.Model):
    # Contract_Type = (
    #     ('Framework', 'Framework contract'),
    #     ('Determined', 'Others'))

    STATUS = (

        ('SIGNED', 'SIGNED'),
        ('CANCELED', 'CANCELED')
    )

    date_created = models.DateField(auto_now_add=True, null=True)
    number = models.IntegerField(null=True)
    name = models.CharField(null=True, max_length=200)
    contractCategory = models.ForeignKey(ContractSettingName, on_delete=models.SET_NULL, null=True, blank=True)
    contractType = models.ForeignKey(ContractSetting, on_delete=models.SET_NULL, null=True, blank=True)
    contract_status = models.CharField(choices=STATUS, max_length=100, default='SIGNED')
    secondParty = models.ForeignKey(SecondParty, on_delete=models.SET_NULL, null=True, blank=True)
    signedDate = models.DateField(blank=True, null=True)
    expirationDate = models.DateField(blank=True, null=True)
    description = models.CharField(max_length=250, null=True, blank=True)
    department = models.ForeignKey(Department, on_delete=models.SET_NULL, max_length=250, null=True)
    departmentUnit = models.ForeignKey(DepartmentMember, on_delete=models.SET_NULL, null=True, blank=True)
    notificationSent = models.BooleanField(default=False)
    notificationSentOn = models.DateField(blank=True, null=True)
    notificationRemindingTimes = models.IntegerField(blank=True, null=True, default=0)
    notificationWaitingInterval = models.IntegerField(blank=True, null=True)
    renewed = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return self.name


class ContractHistory(models.Model):
    contract = models.ForeignKey(Contract, on_delete=models.CASCADE)
    signedDate = models.DateField(blank=True, null=True)
    expirationDate = models.DateField(blank=True, null=True)
    renewDate = models.DateField(blank=True, null=True)
    renewalCounter = models.IntegerField(default=0)

    def __str__(self):
        return f'{self.contract.name} History'

icparsa/models/systemMails.py
from django.db import models


class SystemMail(models.Model):
    number = models.IntegerField(null=True, blank=True)

icparsa/forms/DepartmentForm.py
from django import forms

from icparsa.models import Department


class DepartmentForm(forms.ModelForm):
    class Meta:
        model = Department
        fields = '__all__'

        widgets = {
            'email': forms.EmailInput(attrs={'placeholder': 'Enter email'})
        }

icparsa/views/contractSettingView.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render

from icparsa.decorators import allowed_users
from icparsa.forms.contractSettingForm import ContractSettingForm, ContractSettingNameForm
from icparsa.models.contractSetting import ContractSetting, ContractSettingName


def calculateRemindingTime(expiration_days):
    if expiration_days < 5:
        return 1
    elif 5 <= expiration_days < 15:
        return 3
    else:
        return 5


@allowed_users(allowed_roles=['procurement', 'admin'])
@login_required(login_url='log')
def setupContract(request):
    contractSettingForm = ContractSettingForm()
    if request.method == 'POST':
        contractSettingForm = ContractSettingForm(request.POST)
        if contractSettingForm.is_valid():
            contractSetting = contractSettingForm.save(commit=False)
            expirationDays = contractSetting.expirationDays
            contractSetting.remindingTimes = calculateRemindingTime(expirationDays)
            # contractSettingForm.save()
            contractSetting.save()
        return redirect('liconset')
    context = {'contractSettingForm': contractSettingForm}
    return render(request, 'icparsa/settings/system/contractSetting.html', context)


@login_required(login_url='log')
@allowed_users(allowed_roles=['procurement', 'admin'])
def createContractSettingName(request):
    next_number = ContractSettingName.objects.all().count() + 1
    contractSettingNameForm = ContractSettingNameForm(initial={'number': next_number})
    if request.method == 'POST':
        contractSettingNameForm = ContractSettingNameForm(request.POST)
        if contractSettingNameForm.is_valid():
            contractSettingNameForm.save()
        return redirect('conset')
    context = {'contractSettingNameForm': contractSettingNameForm}
    return render(request, 'icparsa/settings/system/contractSettingName.html', context)


@allowed_users(allowed_roles=['procurement', 'admin'])
@login_required(login_url='log')
def listContractSetup(request):
    contractSetups = ContractSetting.objects.all()
    context = {'contractSetups': contractSetups}
    return render(request, 'icparsa/settings/system/listContractSetting.html', context)


@allowed_users(allowed_roles=['procurement', 'admin'])
@login_required(login_url='log')
def listContractSettingName(request):
    contractSettingName = ContractSettingName.objects.all()
    context = {'contractSettingName': contractSettingName}
    return render(request, 'icparsa/settings/system/listContractSettingName.html', context)


@allowed_users(allowed_roles=['procurement', 'admin'])
@login_required(login_url='log')
def updateContractSetup(request, pk):
    conSet = ContractSetting.objects.get(id=pk)
    conSetForm = ContractSettingForm(instance=conSet)
    if request.method == 'POST':
        conSetForm = ContractSettingForm(request.POST, instance=conSet)
        if conSetForm.is_valid():
            conSetForm.save()
            return redirect('liconset')

    context = {'contractSettingForm': conSetForm, 'conSet': conSet}
    return render(request, 'icparsa/settings/system/contractSetting.html', context)


@allowed_users(allowed_roles=['procurement', 'admin'])
@login_required(login_url='log')
def updateContractSettingName(request, pk):
    conSet = ContractSettingName.objects.get(id=pk)
    conSetForm = ContractSettingNameForm(instance=conSet)
    if request.method == 'POST':
        conSetForm = ContractSettingNameForm(request.POST, instance=conSet)
        if conSetForm.is_valid():
            conSetForm.save()
            return redirect('LiCoSeNa')

    context = {'contractSettingNameForm': conSetForm, 'conSet': conSet}
    return render(request, 'icparsa/settings/system/contractSettingName.html', context)


@allowed_users(allowed_roles=['procurement', 'admin'])
@login_required(login_url='log')
def deleteContractSetup(request, pk):
    conSetToDel = ContractSetting.objects.get(id=pk)
    if request.method == 'POST':
        conSetToDel.delete()
        return redirect('liconset')
    context = {'conSetToDel': conSetToDel}
    return render(request, 'icparsa/settings/system/delConSettings.html', context)


@login_required(login_url='log')
@allowed_users(allowed_roles=['procurement', 'admin'])
def loadContractSettingType(request):
    contractName_id = request.GET.get('contractName_id')
    contractType = ContractSetting.objects.filter(contractName_id=contractName_id)
    context = {'contractType': contractType}
    return render(request, 'icparsa/settings/system/contractTypeDropDown.html', context)

icparsa/views/departmentMemberView.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render

from icparsa.decorators import allowed_users
from icparsa.forms.DepartmentMemberForm import DepartmentMemberForm
from icparsa.models import DepartmentMember, ContractSettingName


@allowed_users(allowed_roles=['admin'])
@login_required(login_url='log')
def createDepartmentMember(request):
    nexNumber = DepartmentMember.objects.all().count() + 1
    departmentMemberForm = DepartmentMemberForm(initial={'number': nexNumber})
    if request.method == 'POST':
        departmentMemberForm = DepartmentMemberForm(request.POST)
        departmentMemberForm.save()
        return redirect('dem')
    context = {'departmentMemberForm': departmentMemberForm}
    return render(request, 'icparsa/settings/system/departmentMember.html', context)


@allowed_users(allowed_roles=['admin'])
@login_required(login_url='log')
def updateDepartmentMember(request, pk):
    unit = DepartmentMember.objects.get(id=pk)
    departmentMemberForm = DepartmentMemberForm(instance=unit)

    if request.method == 'POST':
        departmentMemberForm = DepartmentMemberForm(request.POST, instance=unit)
        if departmentMemberForm.is_valid():
            departmentMemberForm.save()
            return redirect('ldem')
    context = {'departmentMemberForm': departmentMemberForm, 'unit': unit}
    return render(request, 'icparsa/settings/system/departmentMember.html', context)


@login_required(login_url='log')
def listDepartmentMember(request):
    membersList = DepartmentMember.objects.all()
    context = {'membersList': membersList}
    return render(request, 'icparsa/settings/system/listMembers.html', context)


@login_required(login_url='log')
def load_department_members(request):
    department_id = request.GET.get('department_id')
    units = DepartmentMember.objects.filter(department_id=department_id)
    context = {'units': units}
    return render(request, 'icparsa/settings/system/member_drop.html', context)

icparsa/views/departmentView.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render

from icparsa.decorators import allowed_users
from icparsa.forms.DepartmentForm import DepartmentForm
from icparsa.models import Department


@allowed_users(allowed_roles=['admin'])
@login_required(login_url='log')
def createDepartment(request):
    nextNumber = Department.objects.all().count() + 1
    departmentForm = DepartmentForm(initial={'number': nextNumber})
    if request.method == 'POST':
        departmentForm = DepartmentForm(request.POST)
        departmentForm.save()
        return redirect('dem')
    context = {'departmentForm': departmentForm}
    return render(request, 'icparsa/settings/system/department.html', context)


@allowed_users(allowed_roles=['admin'])
@login_required(login_url='log')
def listDepartment(request):
    departmentList = Department.objects.all()
    context = {'departmentList': departmentList}
    return render(request, 'icparsa/settings/system/listDepartment.html', context)


@allowed_users(allowed_roles=['admin'])
@login_required(login_url='log')
def updateDepartment(request, pk):
    dep = Department.objects.get(id=pk)
    departmentForm = DepartmentForm(instance=dep)
    if request.method == 'POST':
        departmentForm = DepartmentForm(request.POST, instance=dep)
        if departmentForm.is_valid():
            departmentForm.save()
            return redirect('dep')

    context = {'departmentForm': departmentForm, 'dep': dep}
    return render(request, 'icparsa/settings/system/department.html', context)

icparsa/views/institutionView.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render

from icparsa.decorators import allowed_users
from icparsa.forms.InstitutionForm import InstitutionForm
from icparsa.models import SecondParty


@allowed_users(allowed_roles=['admin', 'procurement'])
@login_required(login_url='log')
def recordInstitute(request):
    nextNumber = SecondParty.objects.all().count() + 1
    institutionForm = InstitutionForm(initial={'number': nextNumber})
    if request.method == 'POST':
        institutionForm = InstitutionForm(request.POST)
        if institutionForm.is_valid():
            institutionForm.save()
            messages.success(request, 'Service Provider Created !')
            # return redirect('insts')
            institutionForm = InstitutionForm(initial={'number': nextNumber})
    context = {'institutionForm': institutionForm}
    return render(request, 'icparsa/secondParty/institution.html', context)


@allowed_users(allowed_roles=['admin', 'procurement'])
@login_required(login_url='log')
def updateInstitution(request, pk):
    inst = SecondParty.objects.get(id=pk)
    institutionForm = InstitutionForm(instance=inst)
    if request.method == 'POST':
        institutionForm = InstitutionForm(request.POST, instance=inst)
        if institutionForm.is_valid():
            institutionForm.save()
            return redirect('insts')
    context = {'institutionForm': institutionForm, 'inst': inst}
    return render(request, 'icparsa/secondParty/institution.html', context)


@allowed_users(allowed_roles=['admin', 'procurement'])
@login_required(login_url='log')
def deleteInstitution(request, pk):
    inst = SecondParty.objects.get(id=pk)
    if request.method == 'POST':
        inst.delete()
        return redirect('/insts')
    context = {'inst': inst}
    return render(request, 'icparsa/secondParty/delInst.html', context)


@allowed_users(allowed_roles=['admin', 'procurement'])
@login_required(login_url='log')
def searchWithCompanyName(request):
    shaka = request.GET.get('shaka', '')
    if shaka:
        institutionsList = SecondParty.objects.filter(name__icontains=shaka)
    else:
        institutionsList = SecondParty.objects.none()

    context = {'institutionsList': institutionsList, 'shaka': shaka}
    return render(request, 'icparsa/secondParty/institutions.html', context)

icparsa/templates/icparsa/contract/contract.html
{% extends 'icparsa/template/main.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% block content %}


    <div class="row">
        <div class="col-md">
            <div class="card">
                <div class="card-header">
                    <h4 style="font-size: smaller; text-align: center">Record New Contract</h4>
                </div>
            </div>
        </div>
    </div>
    <br>
    <div class="row">
        <div class="col-md">
            <div class="card card-body" style="font-size: x-small">
                <form method="post" action="" id="contractFormId"
                      data-mebdep-url="{% url 'load_department_members_url' %}"
                      data-contract-category-url="{% url 'load_contract_type_url' %}">
                    {% csrf_token %}
                    <div class="col-sm-12 p-4  rounded-1 shadow-sm">
                        <div class="row">
                            <div class="form-group col-3">
                                {{ contractForm.number|as_crispy_field }}
                            </div>
                            <div class="form-group col-3">
                                {{ contractForm.name|as_crispy_field }}
                            </div>
                        </div>

                        <div class="row">

                            <div class="form-group col-3">
                                {{ contractForm.contractCategory|as_crispy_field }}
                            </div>
                            <div class="form-group col-3">
                                {{ contractForm.contractType|as_crispy_field }}
                            </div>
                        </div>
                        <div class="row">

                            <div class="form-group col-3">
                                {{ contractForm.department|as_crispy_field }}
                            </div>
                            <div class="form-group col-3">
                                {{ contractForm.departmentUnit|as_crispy_field }}
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-3">
                                {{ contractForm.contract_status | as_crispy_field }}
                            </div>
                            <div class="col-3">
                                {{ contractForm.secondParty | as_crispy_field }}
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-3">
                                {{ contractForm.signedDate | as_crispy_field }}
                            </div>
                            <div class="col-3">
                                {{ contractForm.expirationDate | as_crispy_field }}
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-6">
                                {{ contractForm.description |as_crispy_field }}
                            </div>
                        </div>
                    </div>
                    <br>

                    <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static"
                         data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel"
                         aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <div class="alert alert-success" role="alert">
                                        <div class="d-flex gap-4">
                                            <span><i class="fa-solid fa-circle-check icon-success"></i></span>
                                            <div>
                                                Contract saved successfully !
                                            </div>
                                        </div>
                                    </div>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">

                                    </button>
                                </div>
                                <div class="modal-body">
                                    Do you want to record another?
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-success" data-bs-dismiss="modal"
                                            id="closeButton"> Yes
                                    </button>
                                    <button type="button" class="btn btn-primary" data-bs-dismiss="modal"
                                            id="addContract">Add Contract
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>

                    <input type="submit" name="Send" value="Save" class="btn btn-sm btn-success">
                    <a href="/conts/" class="btn btn-sm btn-info">
                        <i class="fa-solid fa-list"></i> List
                    </a>

                    <a href="/inst/" class="btn btn-sm btn-outline-secondary">
                        <i class="fa-solid fa-add"></i> Add Company
                    </a>
                    <a href="/consetName/" class="btn btn-sm btn-warning">
                        <i class="fa-solid fa-gears"></i> Contract
                    </a>
                </form>
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script>
        $("#id_department").on("change", function () {
            const url = $("#contractFormId").attr("data-mebdep-url");
            const departmentId = $(this).val();
            $.ajax({
                url: url,
                data: {'department_id': departmentId},
                success: function (data) {
                    console.log(data);
                    $("#id_departmentUnit").html(data)
                }
            });
        });
    </script>
    <script>
        $("#id_contractCategory").on("change", function () {
            const url = $("#contractFormId").attr("data-contract-category-url");
            const contractName_id = $(this).val();
            $.ajax({
                url: url,
                data: {'contractName_id': contractName_id},
                success: function (data) {
                    console.log(data);
                    $("#id_contractType").html(data)
                }
            });
        });
    </script>


    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    {% if messages %}
        {% for message in messages %}
            {% if message.tags == 'success' %}
                <script>
                    $(document).ready(function () {
                        $('#staticBackdrop').modal('show');
                    });
                </script>
                <script>
                    $(document).ready(function () {
                        $('#closeButton').on('click', function () {
                            window.location.href = "{% url 'conts' %}";
                        });
                    });
                </script>
                <script>
                    $(document).ready(function () {
                        $('#addContract').on('click', function () {
                            window.location.href = "/con/";
                        });
                    });
                </script>

            {% endif %}
        {% endfor %}
    {% endif %}

{% endblock %}

icparsa/templates/icparsa/contract/delContract.html
{% extends 'icparsa/template/main.html' %}
{% load crispy_forms_filters %}
{% block content %}
    <br>
    <div class="row text-center">
        <div class="col-md-6">
            <div class="card card-body">
                <p>Are you sure you want to delete "{{ cont }}"? </p>
                <form action="{% url 'delCo' cont.id %}" method="post">
                    {% csrf_token %}
                    <a class="btn btn-warning" href="{% url 'conts' %}"><i class="fa-solid fa-xmark"></i>Cancel</a>
                    <button class="btn btn-danger" type="submit" name="Confirm">
                        <i class="fa-solid fa-check"></i> Confirm
                    </button>


                </form>
            </div>
        </div>
    </div>

{% endblock %}