company/urls.py
from django.urls import path

from company.views.companyEmployeeView import saveEmployee, listEmployee, updateEmployee, recordSystemUserAsEmployee, \
    loadTitle
from company.views.companyView import createCompany, listCompany, updateCompany, deleteCompany
from company.views.departmentView import createDepartment, listDepartment, updateDepartment, deleteDepartment
from company.views.titleView import createCompanyTitle, listTitle, updateTitle, deleteTitle, load_unit, loadDepartment
from company.views.unitView import createUnit, listUnit, updateUnit, deleteUnit, loadUnit
from company.views.userAsEmployeeView import createSignature, displayEmployeeSignature

urlpatterns = [
    path('tit', createCompanyTitle, name='tit'),
    path('lt', listTitle, name='lt'),
    path('upti<str:pk>', updateTitle, name='upti'),
    path('delt<str:pk>', deleteTitle, name='delt'),

    path('dep', createDepartment, name='dep'),
    path('ld', listDepartment, name='ld'),
    path('upde<str:pk>/', updateDepartment, name='upde'),
    path('deld<str:pk>/', deleteDepartment, name='deld'),

    path('cop', createCompany, name='cop'),
    path('lc/', listCompany, name='lc'),
    path('upco/<str:pk>', updateCompany, name='upco'),
    path('delc/<str:pk>', deleteCompany, name='delc'),

    path('cem/', saveEmployee, name='cem'),
    path('lem/', listEmployee, name='lem'),
    path('upem/<str:pk>', updateEmployee, name='upem'),
    path('syem/<int:pk>', recordSystemUserAsEmployee, name='syem'),

    path('cun/', createUnit, name='cun'),
    path('lun/', listUnit, name='lun'),
    path('upun/<str:pk>', updateUnit, name='upun'),
    path('delun/<str:pk>', deleteUnit, name='delun'),
    path('cresig/', createSignature, name='cresig'),
    path('li_em_si/<str:pk>/signature/', displayEmployeeSignature, name='li_em_si'),

    path('ajax/loadUnitDropdown', load_unit, name='loadUnit'),
    path('ajax/loadDepartmentDropdown', loadDepartment, name='load_department'),
    path('ajax/loadTitleDropdown', loadTitle, name='loadTitle')

]

icpars/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("icparsa.urls")),
    path('lem/', include("leaveMan.urls")),
    path('cop/', include("company.urls")),
    path('cor/', include("correspondence.urls")),
    path('filup', include("filemanager.urls")),

]
if settings.DEBUG:
    urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

company/models/companyEmployee.py
from django.db import models

from company.models import Title, Department
from .umumaro import Umumaro


class CompanyEmployee(models.Model):
    number = models.IntegerField(null=True, blank=True)
    emp_code = models.IntegerField(null=True, blank=True)
    first_name = models.CharField(max_length=250, null=True, blank=True)
    last_name = models.CharField(max_length=250, null=True, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    home_phone = models.IntegerField(null=True, blank=True)
    mobile_phone = models.IntegerField(null=True, blank=True)
    home_address = models.CharField(max_length=150, null=True, blank=True)

    hire_date = models.DateField(null=True, blank=True)
    title = models.ForeignKey(Title, on_delete=models.SET_NULL, blank=True, null=True)
    department = models.ForeignKey(Department, on_delete=models.SET_NULL, blank=True, null=True)
    email = models.EmailField(max_length=254, null=True, blank=True)
    role = models.ForeignKey(Umumaro, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    # months_in_institution = models.IntegerField(null=True, blank=True)
    # total_leave_days = models.IntegerField(null=True, blank=True)
    # leave_days_used = models.IntegerField(null=True, blank=True)

leaveMan/models/leave.py
from django.db import models

from company.models import Department, Title, CompanyEmployee


class Leave(models.Model):
    STATUS_OF_LEAVE = [
        ('PENDING', 'PENDING'),
        ('APPROVED', 'APPROVED'),
        ('DENIED', 'DENIED'),
        ('DONE', 'DONE'),
    ]

    number = models.IntegerField(null=True, blank=True)
    employee = models.ForeignKey(CompanyEmployee, on_delete=models.CASCADE, null=True, blank=True)
    months_in_institution = models.IntegerField(null=True, blank=True)
    total_leave_days = models.IntegerField(null=True, blank=True)
    leave_days_used = models.IntegerField(null=True, blank=True, default=0)
    leave_days = models.IntegerField(null=True, blank=True, default=0)
    outDate = models.DateField(null=True, blank=True)
    inDate = models.DateField(null=True, blank=True)
    leave_status = models.CharField(max_length=100, choices=STATUS_OF_LEAVE, default='PENDING')
    approval_one = models.BinaryField(null=True, blank=True)

company/forms/companyForm.py
from django import forms

from company.models.company import Company


class CompanyForm(forms.ModelForm):
    class Meta:
        model = Company
        fields = '__all__'

        widgets = {
            'email': forms.EmailInput(attrs={'placeholder': 'Enter email'})
        }

company/forms/departmentForm.py
from django import forms

from company.models.department import Department


class DepartmentForm(forms.ModelForm):
    class Meta:
        model = Department
        fields = '__all__'

        widgets = {
            'email': forms.EmailInput(attrs={'placeholder': 'Enter email'})
        }

company/forms/userAsEmployeeSignatureForm.py
from django import forms
from django.utils.safestring import mark_safe

from company.models import EmployeeAsUserSignature


# class SignaturePadWidget(forms.Widget):
#     template_name = 'company/employee/signaturePad.html'  # Create this template
#
#     def render(self, name, value, attrs=None, renderer=None):
#         return mark_safe(f'<div id="{name}_signature_pad"></div>')
#
#     def value_from_datadict(self, data, files, name):
#         # Handle form submission and retrieve the signature data
#         return data.get(name, None)


class UserAsEmployeeSignatureForm(forms.ModelForm):
    class Meta:
        model = EmployeeAsUserSignature
        fields = '__all__'

        widgets = {
            'signature_password': forms.PasswordInput(attrs={'placeholder': 'Enter password'}),

        }

company/views/companyEmployeeView.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import redirect, render, get_object_or_404

from company.forms.employeeForm import EmployeeForm
from company.models import CompanyEmployee, Unit, Department, Title
from icparsa.decorators import allowed_users


@login_required(login_url='log')
@allowed_users(allowed_roles=['admin'])
def saveEmployee(request):
    next_number = CompanyEmployee.objects.all().count() + 1
    employeeForm = EmployeeForm(initial={'number': next_number})
    if request.method == 'POST':
        employeeForm = EmployeeForm(request.POST)
        employeeForm.save()
        return redirect('cem')
    context = {'employeeForm': employeeForm}
    return render(request, 'company/employee/employee.html', context)


@login_required(login_url='log')
@allowed_users(allowed_roles=['admin'])
def listEmployee(request):
    employeeList = CompanyEmployee.objects.all()
    context = {'employeeList': employeeList}
    return render(request, 'company/employee/listEmployee.html', context)


def updateEmployee(request, pk):
    emp = CompanyEmployee.objects.get(id=pk)
    empForm = EmployeeForm(instance=emp)
    if request.method == 'POST':
        empForm = EmployeeForm(request.POST, instance=emp)
        if empForm.is_valid():
            empForm.save()
            return redirect('lem')
    context = {'employeeForm': empForm}
    return render(request, 'company/employee/employee.html', context)


def recordSystemUserAsEmployee(request, pk):
    syst_user = get_object_or_404(User, id=pk)
    employee = CompanyEmployee()
    next_number = CompanyEmployee.objects.all().count() + 1
    for field in syst_user._meta.fields:
        if field.name in [f.name for f in employee._meta.fields]:
            setattr(employee, field.name, getattr(syst_user, field.name))
    employee.first_name = syst_user.first_name
    employee.last_name = syst_user.last_name

    if request.method == 'POST':
        empForm = EmployeeForm(request.POST, instance=employee)
        if empForm.is_valid():
            empForm.save()
            # return redirect('syem', pk=employee.pk)
            return redirect('home')

    else:
        empForm = EmployeeForm(initial={'number': next_number}, instance=employee)

    context = {'employeeForm': empForm}
    return render(request, 'company/employee/employee.html', context)


def loadTitle(request):
    department_id = request.GET.get('department_id')
    title = Title.objects.filter(department_id=department_id).order_by('name')
    context = {'title': title}
    return render(request, 'company/title/titleDropDown.html', context)


def load_unit(request):
    department_id = request.GET.get('department_id')
    unit = Unit.objects.filter(department_id=department_id)
    context = {'unit': unit}
    return render(request, 'company/unit/unitDropDown.html', context)


def loadDepartment(request):
    company_id = request.GET.get('company_id')
    department = Department.objects.filter(company_id=company_id)
    context = {'department': department}
    return render(request, 'company/department/departmentDropDown.html', context)

company/views/companyView.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render

from company.forms.companyForm import CompanyForm
from company.models import Company
from icparsa.decorators import allowed_users


@login_required(login_url='log')
@allowed_users(allowed_roles=['admin'])
def createCompany(request):
    next_number = Company.objects.all().count() + 1
    companyForm = CompanyForm(initial={'number': next_number})
    if request.method == 'POST':
        companyForm = CompanyForm(request.POST)
        companyForm.save()
        return redirect('lc')
    context = {'companyForm': companyForm}
    return render(request, 'company/company.html', context)


@login_required(login_url='log')
@allowed_users(allowed_roles=['admin'])
def listCompany(request):
    companyList = Company.objects.all()
    context = {'companyList': companyList}
    return render(request, 'company/listCompany.html', context)


@login_required(login_url='log')
@allowed_users(allowed_roles=['admin'])
def updateCompany(request, pk):
    company = Company.objects.get(id=pk)
    companyForm = CompanyForm(instance=company)
    if request.method == 'POST':
        companyForm = CompanyForm(request.POST, instance=company)
        if companyForm.is_valid():
            companyForm.save()
            return redirect('lc')

    context = {'companyForm': companyForm, 'company': company}
    return render(request, 'company/company.html', context)


@login_required(login_url='log')
@allowed_users(allowed_roles=['admin'])
def deleteCompany(request, pk):
    company = Company.objects.get(id=pk)
    if request.method == 'POST':
        company.delete()
        return redirect('lt')
    context = {'company': company}
    return render(request, 'company/deleteCompany.html', context)

company/views/departmentView.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render

from company.forms.departmentForm import DepartmentForm
from company.models.department import Department
from icparsa.decorators import allowed_users


@login_required(login_url='log')
@allowed_users(allowed_roles=['admin'])
def createDepartment(request):
    next_number = Department.objects.all().count() + 1
    departmentForm = DepartmentForm(initial={'number': next_number})
    if request.method == 'POST':
        departmentForm = DepartmentForm(request.POST)
        departmentForm.save()
        return redirect('ld')
    context = {'departmentForm': departmentForm}
    return render(request, 'company/department.html', context)


@login_required(login_url='log')
def listDepartment(request):
    departmentList = Department.objects.all()
    context = {'listDepartment': departmentList}
    return render(request, 'company/listDepartment.html', context)


@login_required(login_url='log')
@allowed_users(allowed_roles=['admin'])
def updateDepartment(request, pk):
    department = Department.objects.get(id=pk)
    departmentForm = DepartmentForm(instance=department)
    if request.method == 'POST':
        departmentForm = DepartmentForm(request.POST, instance=department)
        if departmentForm.is_valid():
            departmentForm.save()
            return redirect('ld')

    context = {'departmentForm': departmentForm, 'department': department}
    return render(request, 'company/department.html', context)


@login_required(login_url='log')
@allowed_users(allowed_roles=['admin'])
def deleteDepartment(request, pk):
    department = Department.objects.get(id=pk)
    if request.method == 'POST':
        department.delete()
        return redirect('ld')
    context = {'department': department}
    return render(request, 'company/deleteDepartment.html', context)

company/views/titleView.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render

from company.forms.titleForm import TitleForm
from company.models import Unit, Department
from company.models.title import Title
from icparsa.decorators import allowed_users


@login_required(login_url='log')
@allowed_users(allowed_roles=['admin'])
def createCompanyTitle(request):
    next_number = Title.objects.all().count() + 1
    titleForm = TitleForm(initial={'number': next_number})
    if request.method == 'POST':
        titleForm = TitleForm(request.POST)
        titleForm.save()
        return redirect('lt')
    context = {'titleForm': titleForm}
    return render(request, 'company/title.html', context)


@login_required(login_url='log')
def listTitle(request):
    titleList = Title.objects.all()

    context = {'titleList': titleList}
    return render(request, 'company/listTitle.html', context)


@login_required(login_url='log')
@allowed_users(allowed_roles=['admin'])
def updateTitle(request, pk):
    title = Title.objects.get(id=pk)
    titleForm = TitleForm(instance=title)
    if request.method == 'POST':
        titleForm = TitleForm(request.POST, instance=title)
        if titleForm.is_valid():
            titleForm.save()
            return redirect('lt')
    context = {'titleForm': titleForm, 'title': title}
    return render(request, 'company/title.html', context)


@login_required(login_url='log')
@allowed_users(allowed_roles=['admin'])
def deleteTitle(request, pk):
    title = Title.objects.get(id=pk)
    if request.method == 'POST':
        title.delete()
        return redirect('/lt')
    context = {'title': title}
    return render(request, 'company/deleteTitle.html', context)


def load_unit(request):
    department_id = request.GET.get('department_id')
    unit = Unit.objects.filter(department_id=department_id)
    context = {'unit': unit}
    return render(request, 'company/unit/unitDropDown.html', context)


def loadDepartment(request):
    company_id = request.GET.get('company_id')
    department = Department.objects.filter(company_id=company_id)
    context = {'department': department}
    return render(request, 'company/department/departmentDropDown.html', context)

company/views/unitView.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render

from company.forms.unitForm import UnitForm
from company.models import Unit, Department
from icparsa.decorators import allowed_users


@login_required(login_url='log')
@allowed_users(allowed_roles=['admin'])
def createUnit(request):
    next_number = Unit.objects.all().count() + 1
    unitForm = UnitForm(initial={'number': next_number})
    if request.method == 'POST':
        unitForm = UnitForm(request.POST)
        unitForm.save()
        return redirect('lun')
    context = {'unitForm': unitForm}
    return render(request, 'company/unit.html', context)


@login_required(login_url='log')
def listUnit(request):
    unitList = Unit.objects.all()
    context = {'unitList': unitList}
    return render(request, 'company/listUnit.html', context)


@login_required(login_url='log')
@allowed_users(allowed_roles=['admin'])
def updateUnit(request, pk):
    unit = Unit.objects.get(id=pk)
    unitForm = UnitForm(instance=unit)
    if request.method == 'POST':
        unitForm = UnitForm(request.POST, instance=unit)
        if unitForm.is_valid():
            unit.save()
            return redirect('lun')

    context = {'unitForm': unitForm, 'unit': unit}
    return render(request, 'company/unit.html', context)


@login_required(login_url='log')
@allowed_users(allowed_roles=['admin'])
def deleteUnit(request, pk):
    unit = Unit.objects.get(id=pk)
    if request.method == 'POST':
        unit.delete()
        return redirect('/lun')
    context = {'unit': unit}
    return render(request, 'company/deleteUnit.html', context)


def loadUnit(request):
    department_id = request.GET.get('unit_id')
    unit = Unit.objects.filter(department_id=department_id)
    context = {'unit': unit}
    return render(request, 'company/unit/unitDropDown.html', context)


def loadDepartment(request):
    company_id = request.GET.get('department_id')
    department = Department.objects.filter(company_id=company_id)
    context = {'department': department}
    return render(request, 'company/department/departmentDropDown.html', context)

company/templates/company/employee/employee.html
{% extends 'icparsa/template/main.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% block content %}


    <div class="row">
        <div class="col-md">
            <div class="card">
                <div class="card-header">
                    <h4 style="font-size: smaller; text-align: center">Complete Registration</h4>
                </div>
            </div>
        </div>
    </div>
    <br>
    <div class="row">
        <div class="col-md">
            <div class="card card-body" style="font-size: x-small">
                <form method="post" action="" id="empFormId"
                      title_url_loader= {% url 'loadTitle' %}>
                    {% csrf_token %}
                    <div class="row">
                        <div class="form-group col-2">
                            {{ employeeForm.number|as_crispy_field }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-2">
                            {{ employeeForm.first_name|as_crispy_field }}
                        </div>
                        <div class="form-group col-2">
                            {{ employeeForm.last_name|as_crispy_field }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-2">
                            {{ employeeForm.birth_date|as_crispy_field }}
                        </div>
                        <div class="form-group col-2">
                            {{ employeeForm.home_phone|as_crispy_field }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-2">
                            {{ employeeForm.mobile_phone|as_crispy_field }}
                        </div>
                        <div class="form-group col-2">
                            {{ employeeForm.email|as_crispy_field }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-2">
                            {{ employeeForm.home_address|as_crispy_field }}
                        </div>
                        <div class="form-group col-2">
                            {{ employeeForm.hire_date|as_crispy_field }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-2">
                            {{ employeeForm.department|as_crispy_field }}
                        </div>
                        <div class="form-group col-2">
                            {{ employeeForm.title|as_crispy_field }}
                        </div>
                    </div>
                    <br>
                    <input type="submit" name="Send" class="btn btn-sm btn-info">
                    <a href="/cop/lem" class="btn btn-sm btn-info">
                        <i class="fa-solid fa-list"></i> List
                    </a>
                </form>
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script>

        $("#id_department").on("change", function () {
            const url = $("#empFormId").attr("title_url_loader");
            const departmentId = $(this).val();
            $.ajax({
                url: url,
                data: {'department_id': departmentId},
                success: function (data) {
                    console.log(data);
                    $("#id_title").html(data)
                }
            });
        });

    </script>

{% endblock %}

company/templates/company/employee/employeeSignature.html
{% extends 'icparsa/template/main.html' %}
{% load static %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% block content %}

    <link rel="stylesheet" type="text/css" href="{% static '/css/pad.css' %}">
    <div class="row">
        <div class="col-md">
            <div class="card">
                <div class="card-header">
                    <h4 style="font-size: smaller; text-align: center">Complete Registration</h4>
                </div>
            </div>
        </div>
    </div>
    <br>
    <div class="row">
        <div class="col-md">
            <div class="card card-body bg-secondary" style="font-size: x-small">
                <h1>Employee Signature</h1>
                <div class="overflow-auto bg-light" style="max-height: 200px; max-width: 300px">
                    {% if signature %}
                        <img src="{{ signature }}" alt="Employee Signature">
                    {% else %}
                        <p>No signature available.</p>
                    {% endif %}
                </div>

            </div>
        </div>
    </div>

    <script src="{% static 'js/pad.js' %}"></script>
{% endblock %}

company/templates/company/employee/listEmployee.html
{% extends 'icparsa/template/main.html' %}

{% block content %}
    <br/>
    <div class="row">
        <div class="col-md">
            <div class="card">
                <div class="card-header">
                    <form>
                        <div class="row">
                            <div class="col-2 p-0">
                                <a class="btn btn-outline-primary btn-sm p-1" href="/cop/cem">
                                    <i class="fa fa-user-plus fa-align-left"></i>
                                    Add Employee
                                </a>
                            </div>
                            <div class="col-2 p-0">
                                <a class="btn btn-outline-primary btn-sm p-1" href="/cop/dep">

                                    Add Department
                                </a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <br/>
    <div class="row">
        <div class="col-md">
            <div class="card card-body" style="font-size: x-small">
                <table class="table table-striped table-bordered table-sm small " id="tbl">

                    <tr>
                        <th>No</th>
                        <th>First Name</th>
                        <th>Last Name</th>
                        <th>Birth Date</th>
                        <th>Home Telephone</th>
                        <th>Home Phone</th>
                        <th>Email</th>
                        <th>Address</th>
                        <th>Department</th>
                        <th>Title</th>
                        <th>Hired Date</th>
                        <th colspan="3">Action</th>
                    </tr>
                    {% for e in employeeList %}
                        <tr>
                            <td>{{ e.number }}</td>
                            <td data-bs-toggle="collapse" role="button"
                                data-bs-target="#employeeLeaveHistory{{ e.id }}"
                                aria-controls="employeeLeaveHistory{{ e.id }}">{{ e.first_name }}
                                {#                                <i class="bi bi-three-dots-vertical"></i>#}
                                <i class="fa-solid fa-caret-down"></i>
                            </td>
                            <td>{{ e.last_name }}</td>
                            <td>{{ e.birth_date }}</td>
                            <td>{{ e.home_phone }}</td>
                            <td>{{ e.mobile_phone }}</td>
                            <td>{{ e.home_address }}</td>
                            <td>{{ e.email }}</td>
                            <td>{{ e.department }}</td>
                            <td>{{ e.title }}</td>
                            <td>{{ e.hire_date }}</td>
                            <td><a href="{% url 'gl' e.id %}" class="btn btn-sm btn-outline-info"
                                   style="font-size: xx-small">
                                <i class="fa-solid fa-person-walking-arrow-right" style="font-size: xx-small"></i> Leave</a>
                            </td>
                            <td><a
                                    style="font-size: xx-small" href="{% url 'upem' e.id %}"
                                    class="btn btn-sm btn-warning">
                                <i style="font-size: xx-small" class="fa-solid fa-pen-to-square"></i>
                                Update</a></td>
                            <td>
                        </tr>
                        <tr>
                            <td colspan="100%" class="accordion-body collapse" id="employeeLeaveHistory{{ e.id }}">
                                <table class="table table-striped table-bordered border-info table-sm small">
                                    <thead class="thead-light">
                                    <th>Number</th>
                                    <th>Total Months</th>
                                    <th>Total Leave_Days</th>
                                    <th>Used Leave_Days</th>
                                    <th>Left On</th>
                                    <th>Back On</th>
                                    <th>Previous Leave_Days</th>
                                    <th colspan="4">Action</th>
                                    </thead>
                                    <tbody>
                                    {% for el in e.leave_set.all %}
                                        <tr>
                                            <td>{{ el.number }}</td>
                                            <td>{{ el.months_in_institution }}</td>
                                            <td>{{ el.total_leave_days }}</td>
                                            <td>{{ el.leave_days_used }}</td>
                                            <td>{{ el.outDate }}</td>
                                            <td>{{ el.inDate }}</td>
                                            <td>{{ el.leave_days }}</td>
                                            <td><a href="{% url 'loadleave' el.id %}">Generate</a> </td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </td>

                        </tr>


                    {% endfor %}
                </table>

            </div>

        </div>
    </div>

{% endblock %}

company/templates/company/employee/signature.html
{% extends 'icparsa/template/main.html' %}
{% load static %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% block content %}

<link rel="stylesheet" type="text/css" href="{% static '/css/pad.css' %}">
<div class="row">
    <div class="col-md">
        <div class="card">
            <div class="card-header">
                <h4 style="font-size: smaller; text-align: center">Complete Registration</h4>
            </div>
        </div>
    </div>
</div>
<br>
<div class="row">
    <div class="col-md">
        <div class="card card-body" style="font-size: x-small">
            <form action="" method="POST" class="signature-pad-form">
                {% csrf_token %}

                <div class="row">
                    <div class="col-8">
                        {{ signatureForm.employee|as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-8">
                        {{ signatureForm.signature_password|as_crispy_field }}
                    </div>
                </div>

                <p>
                    <b>Signature</b>
                </p>

                <canvas height="200" width="500" class="signature-pad"></canvas>
                <input type="hidden" name="digital_signature" id="signature-input">
                <a href="#" class="clear-button btn btn-sm btn-warning">
                    <i class="fa-solid fa-broom"></i> Clear
                </a>

                <button class="submit-button btn btn-sm bg-dark" type="submit">
                    <i class="fa-solid fa-sd-card"></i> SUBMIT
                </button>
            </form>
        </div>
    </div>
</div>

<script src="{% static 'js/pad.js' %}"></script>
{% endblock %}

company/templates/company/employee/signaturePad.html
<div>
    <canvas id="signature-pad" class="signature-pad" width=400 height=200></canvas>
    <button type="button" id="clear-signature">Clear</button>
    <input type="hidden" name="{{ name }}" id="{{ name }}_input">
</div>
<script>
    document.addEventListener("DOMContentLoaded", function() {
        var canvas = document.getElementById("signature-pad");
        var clearButton = document.getElementById("clear-signature");
        var hiddenInput = document.getElementById("{{ name }}_input");
        var signaturePad = new SignaturePad(canvas);

        clearButton.addEventListener("click", function() {
            signaturePad.clear();
            hiddenInput.value = '';
        });

        document.querySelector('form').addEventListener('submit', function() {
            if (!signaturePad.isEmpty()) {
                hiddenInput.value = signaturePad.toDataURL();
            }
        });
    });
</script>